document.addEventListener("DOMContentLoaded", function () {
    const cityBanner = document.getElementById("city-banner");
    const cityTitle = document.getElementById("city-title");
    const citylookingTitle = document.getElementById("city-looking-chef-title")
    const cityDescription = document.getElementById("city-description");
    const citySeoContent = document.getElementById("city-seo-content")
    const cityAreaTitle = document.getElementById("city-area-title")
    const cityArea = document.getElementById("city-area-list")
    const localityBanner = document.getElementById("locality-banner");
    const localityTitle = document.getElementById("locality-title");
    const localitylookingTitle = document.getElementById("locality-looking-chef-title")
    const localityDescription = document.getElementById("locality-description");
    const localitySeoContent = document.getElementById("locality-seo-content")

    // Define city-specific data
    // Define city-specific data
    const cityData = {
        Delhi: {
            bannerImage: "content/img/OIP1.jpg",
            cityLocalitiesList:
                [
                    { name: "Adarsh Nagar", },
                    { name: "adchini", },
                    { name: "Ajmeri Gate", },
                    { name: "akshardham", },
                    { name: "Alaknanda", },
                    { name: "Aman Vihar", },
                    { name: "Amar Colony", },
                    { name: "Ambedkar Nagar", },
                    { name: "Amrit Nagar", },
                    { name: "Amritpuri", },
                    { name: "Anand Lok", },
                    { name: "Anand Niketan" },
                    { name: "Anand Parbat" },
                    { name: "Anand Vihar" },
                    { name: "Andrews Ganj" },
                    { name: "Ansari Nagar East" },
                    { name: "Aradhna Enclave" },
                    { name: "Arjun Garh" },
                    { name: "Arjun Nagar" },
                    { name: "Arya Nagar" },
                    { name: "Ashok Nagar" },
                    { name: "Ashok Vihar" },
                    { name: "Ashoka Niketan" },
                    { name: "Ashram" },
                    { name: "Asiad Village" },
                    { name: "Asola" },
                    { name: "Aya Nagar" },
                    { name: "Azad Nagar" },
                    { name: "Azadpur" },
                    { name: "Badarpur" },
                    { name: "Batla house" },
                    { name: "Bawana" },
                    { name: "Bengali Market" },
                    { name: "Ber Sarai" },
                    { name: "Bhagya Vihar" },
                    { name: "Bhajanpura" },
                    { name: "Bhera Enclave" },
                    { name: "Bhikaji Cama Place" },
                    { name: "Budh Nagar" },
                    { name: "Chanakya Place" },
                    { name: "Chanakyapuri" },
                    { name: "Chander Nagar" },
                    { name: "Chandni Chowk" },
                    { name: "Chattarpur" },
                    { name: "Chawri Bazar" },
                    { name: "Chirag Delhi" },
                    { name: "Chirag Enclave" },
                    { name: "Chittaranjan Park" },
                    { name: "Civil Lines" },
                    { name: "Commonwealth Games Village" },
                    { name: "Connaught Place" },
                    { name: "CR Park" },
                    { name: "Dakshini Pitampura" },
                    { name: "Dakshinpuri" },
                    { name: "Darave" },
                    { name: "Daryaganj" },
                    { name: "Dayanand Colony" },
                    { name: "Dayanand Vihar" },
                    { name: "Defence Colony" },
                    { name: "Defence Enclave" },
                    { name: "Delhi Cantonment" },
                    { name: "Deoli" },
                    { name: "Dhansa" },
                    { name: "Dharampura" },
                    { name: "Dhaula Kuan" },
                    { name: "Dilshad Garden" },
                    { name: "Diplomatic Enclave" },
                    { name: "Dr Ambedkar Nagar" },
                    { name: "Dwarka" },
                    { name: "East Of Kailash" },
                    { name: "Fatehpuri" },
                    { name: "Freedom Fighter Enclave" },
                    { name: "Friends Colony" },
                    { name: "G T Karnal Road Industrial Area" },
                    { name: "Gagan Vihar" },
                    { name: "Gandhi Nagar" },
                    { name: "Gautam Nagar" },
                    { name: "Geeta Colony" },
                    { name: "Geetanjali Enclave" },
                    { name: "Ghaffar Manzil Colony" }

                ]
        },
        Gurugram: {
            bannerImage: "content/img/OIP1.jpg",
            cityLocalitiesList: [
                { name: "Ardee city" },
                { name: "Arjun Nagar" },
                { name: "Ashok Vihar Phase I" },
                { name: "Badshapur" },
                { name: "Chakkarpur" },
                { name: "Dlf Phase 1" },
                { name: "Dlf Phase 2" },
                { name: "Dlf Phase 3" },
                { name: "Dlf Phase 4" },
                { name: "Dlf Phase 5" },
                { name: "Fazilpur" },
                { name: "Feroz Gandhi Colony" },
                { name: "Gandhi Nagar" },
                { name: "Garhi Harsaru" },
                { name: "Golf Course Extension" },
                { name: "Greenwood city" },
                { name: "Hans Enclave" },
                { name: "Hari Nagar" },
                { name: "Heera Nagar" },
                { name: "Islampur" },
                { name: "Jharsa" },
                { name: "Jyoti Park" },
                { name: "Kadipur" },
                { name: "Khandsa" },
                { name: "Krishna Colony" },
                { name: "Laxman Vihar" },
                { name: "Madan Puri" },
                { name: "Malibu Town" },
                { name: "Manesar Sector M1" },
                { name: "May Field Gardens" },
                { name: "MG road" },
                { name: "Model Town" },
                { name: "Mohyal Colony" },
                { name: "Nathupur" },
                { name: "New Basti" },
                { name: "New Colony" },
                { name: "New Palam Vihar" },
                { name: "Pace city" },
                { name: "Palam Vihar" },
                { name: "Pataudi Sector 1" },
                { name: "Patel Nagar" },
                { name: "Rajendra Park" },
                { name: "Rajiv Nagar" },
                { name: "Ram Nagar" },
                { name: "Ratan Vihar" },
                { name: "Ravi Nagar" },
                { name: "Rosewood city" },
                { name: "Sadar Bazar" },
                { name: "Saraswati Kunj" },
                { name: "Saraswati Vihar" },
                { name: "Sector 1" },
                { name: "Sector 10" },
                { name: "Sector 100" },
                { name: "Sector 101" },
                { name: "Sector 102" },
                { name: "Sector 103" },
                { name: "Sector 104" },
                { name: "Sector 105" },
                { name: "Sector 106" },
                { name: "Sector 107" },
                { name: "Sector 108" },
                { name: "Sector 109" },
                { name: "Sector 11" },
                { name: "Sector 110" },
                { name: "Sector 111" },
                { name: "Sector 112" },
                { name: "Sector 113" },
                { name: "Sector 114" },
                { name: "Sector 115" },
                { name: "Sector 12" },
                { name: "Sector 13" },
                { name: "Sector 14" },
                { name: "Sector 15 Part I" },
                { name: "Sector 16" },
                { name: "Sector 17" },
                { name: "Sector 18" },
                { name: "Sector 19" },
                { name: "Sector 2" },
                { name: "Sector 20" },
                { name: "Sector 21" },
                { name: "Sector 22" },
                { name: "Sector 23" },
                { name: "Sector 24" },
                { name: "Sector 25" },
                { name: "Sector 26" },
                { name: "Sector 27" },
                { name: "Sector 28" },
                { name: "Sector 29" },
                { name: "Sector 3" },
                { name: "Sector 30" },
                { name: "Sector 31" },
                { name: "Sector 32" },
                { name: "Sector 33" },
                { name: "Sector 34" },
                { name: "Sector 35" },
                { name: "Sector 36" },
                { name: "Sector 37 Part I Industrial" },
                { name: "Sector 38" },
                { name: "Sector 39" },
                { name: "Sector 4" },
                { name: "Sector 41" },
                { name: "Sector 42" },
                { name: "Sector 43" },
                { name: "Sector 44" },
                { name: "Sector 45" },
                { name: "Sector 46" },
                { name: "Sector 47" },
                { name: "Sector 48" },
                { name: "Sector 49" },
                { name: "Sector 5" },
                { name: "Sector 50" },
                { name: "Sector 51" },
                { name: "Sector 52" },
                { name: "Sector 53" },
                { name: "Sector 54" },
                { name: "Sector 55" },
                { name: "Sector 56" },
                { name: "Sector 57" },
                { name: "Sector 58" },
                { name: "Sector 59" }
            ]
        },
        Ghaziabad: {
            bannerImage: "content/img/OIP1.jpg",
            cityLocalitiesList: [
                { "name": "Abhay Khand" },
                { "name": "Ahinsa Khand" },
                { "name": "Amrit Nagar" },
                { "name": "Ankur Vihar" },
                { "name": "Avantika" },
                { "name": "Baghpat" },
                { "name": "Bamheta" },
                { "name": "Behta Colony" },
                { "name": "Behta Hazipur" },
                { "name": "Bhim Nagar" },
                { "name": "Bhopura" },
                { "name": "Bhram Puri" },
                { "name": "Bhuapur" },
                { "name": "Brij Vihar" },
                { "name": "Budh Vihar" },
                { "name": "Chander Nagar" },
                { "name": "Chhapraula" },
                { "name": "Chipiyana Buzurg" },
                { "name": "Chiranjiv Vihar" },
                { "name": "Crossings Republik" },
                { "name": "Dadri" },
                { "name": "Dasna" },
                { "name": "Daulatpur" },
                { "name": "Defence Colony" },
                { "name": "Dilshad Garden" },
                { "name": "Duhai" },
                { "name": "Dundahera" },
                { "name": "Gagan Vihar" },
                { "name": "Gandhi Nagar" },
                { "name": "Ganeshpuri" },
                { "name": "Garhmukteshwar" },
                { "name": "Ghantaghar" },
                { "name": "Ghukna" },
                { "name": "Govindpuram" },
                { "name": "Gulab Vatika" },
                { "name": "Gyan Khand" },
                { "name": "Hapur" },
                { "name": "Hindan Residential Area" },
                { "name": "Indirapuram" },
                { "name": "Indraprastha" },
                { "name": "Jassipur" },
                { "name": "Jawahar Nagar" },
                { "name": "Judges Enclave" },
                { "name": "Kamla Nehru Nagar" },
                { "name": "Kaushambhi" },
                { "name": "Kavi Nagar" },
                { "name": "Kavi Nagar Industrial Area" },
                { "name": "Kot Gaon" },
                { "name": "Krishna Vihar" },
                { "name": "Lohia Nagar" },
                { "name": "Loni" },
                { "name": "Loni Industrial Area" },
                { "name": "Madhopura" },
                { "name": "Mahurali" },
                { "name": "Maliwara" },
                { "name": "Marium Nagar" },
                { "name": "Masuri" },
                { "name": "Meerut Road Industrial Area" },
                { "name": "Mirzapur" },
                { "name": "Model Town" },
                { "name": "Modi Nagar" },
                { "name": "Mohan Meakin Industrial Estate" },
                { "name": "Mohan Nagar" },
                { "name": "Morta" },
                { "name": "Morti" },
                { "name": "Murad Nagar" },
                { "name": "Nai Basti Dundahera" },
                { "name": "Nandgram" },
                { "name": "Nasbandi Colony" },
                { "name": "Naya Ganj" },
                { "name": "Neelmani Colony" },
                { "name": "Nehru Nagar" },
                { "name": "New Vijay Nagar" },
                { "name": "NH 24" },
                { "name": "Niti Khand I" },
                { "name": "Niti Khand-Indirapuram" },
                { "name": "Nyay Khand I" },
                { "name": "Pandav Nagar" },
                { "name": "Pasaunda" },
                { "name": "Patel Nagar I" }
            ]
        },
        Faridabad: {
            bannerImage: "content/img/OIP1.jpg",
            cityLocalitiesList: [
                { "name": "Adarsh Colony" },
                { "name": "Agwanpur" },
                { "name": "Ajit Nagar" },
                { "name": "Ajronda" },
                { "name": "ALL SECTORS" },
                { "name": "Amru" },
                { "name": "Anangpur" },
                { "name": "Ankhir" },
                { "name": "Aravali" },
                { "name": "Aravali Vihar" },
                { "name": "Arya Nagar" },
                { "name": "Ashoka Enclave" },
                { "name": "Badarpur Border" },
                { "name": "Badkhal" },
                { "name": "Ballabhgarh" },
                { "name": "Barauli" },
                { "name": "Basantpur" },
                { "name": "Basilva Colony" },
                { "name": "Bhatia Colony" },
                { "name": "Bhoor Colony" },
                { "name": "Bhopani" },
                { "name": "Camp Market" },
                { "name": "Chandpur" },
                { "name": "Charmwood Village" },
                { "name": "Chawla Colony" },
                { "name": "Dabua Colony" },
                { "name": "Dayal Bagh" },
                { "name": "Dayal Basti" },
                { "name": "Dayalpur" },
                { "name": "Dhauj" },
                { "name": "Dher Colony" },
                { "name": "DLF Industrial Area" },
                { "name": "Faridpur" },
                { "name": "Friends Colony" },
                { "name": "Frontier Colony" },
                { "name": "Fruit Garden" },
                { "name": "Hodal" },
                { "name": "Housing Board colony" },
                { "name": "HUDA Sector 2" },
                { "name": "Indira Gandhi Colony" },
                { "name": "Indraprastha Colony" },
                { "name": "Jasna" },
                { "name": "Jawahar Colony" },
                { "name": "Jeevan Nagar" },
                { "name": "Jiwan Nagar" },
                { "name": "Kabulpur Bangar" },
                { "name": "Kanoongo Maholla" },
                { "name": "Kant Enclave" },
                { "name": "Kanungo Maholla" },
                { "name": "Kanwara" },
                { "name": "Kapra Colony" },
                { "name": "Karna" },
                { "name": "Katan Pahari" },
                { "name": "Krishna Colony" },
                { "name": "Lakewood city" },
                { "name": "Lakkarpur" },
                { "name": "Lane Pura" },
                { "name": "Lohagrah" },
                { "name": "Manjhawali" },
                { "name": "Mewla Maharajpur" },
                { "name": "Mohan Nagar" },
                { "name": "Moti Colony" },
                { "name": "Mujesar" },
                { "name": "Neelam Bata Colony" },
                { "name": "Neharpar" },
                { "name": "Nehru Colony" },
                { "name": "New Baselwa Colony" },
                { "name": "New Colony" },
                { "name": "Old Faridabad" },
                { "name": "Pali Village" },
                { "name": "Panchwati Colony" },
                { "name": "Panna Vihar" },
                { "name": "Piyala" },
                { "name": "Prakash Vihar" },
                { "name": "Prithla" },
                { "name": "Railway Colony" },
                { "name": "Rajeev Nagar" },
                { "name": "Rajiv Nagar" },
                { "name": "Rajpur Kalan" },
                { "name": "Ram Nagar" }
                // Add more localities here
            ]

        },
        Noida: {
            bannerImage: "content/img/OIP1.jpg",
            cityLocalitiesList: [
                { "name": "Ambedkar city" },
                { "name": "Baraula" },
                { "name": "Bhangel" },
                { "name": "Hajipur" },
                { "name": "Indirapuram" },
                { "name": "Mamura" },
                { "name": "Noida Extension" },
                { "name": "Parthala Khanjarpur" },
                { "name": "Sarfbad" },
                { "name": "Sector 1" },
                { "name": "Sector 10" },
                { "name": "Sector 100" },
                { "name": "Sector 101" },
                { "name": "Sector 102" },
                { "name": "Sector 103" },
                { "name": "Sector 104" },
                { "name": "Sector 105" },
                { "name": "Sector 106" },
                { "name": "Sector 107" },
                { "name": "Sector 108" },
                { "name": "Sector 109" },
                { "name": "Sector 110" },
                { "name": "Sector 111" },
                { "name": "Sector 112" },
                { "name": "Sector 113" },
                { "name": "Sector 114" },
                { "name": "Sector 115" },
                { "name": "Sector 116" },
                { "name": "Sector 117" },
                { "name": "Sector 118" },
                { "name": "Sector 119" },
                { "name": "Sector 12" },
                { "name": "Sector 120" },
                { "name": "Sector 121" },
                { "name": "Sector 122" },
                { "name": "Sector 123" },
                { "name": "Sector 124" },
                { "name": "Sector 125" },
                { "name": "Sector 126" },
                { "name": "Sector 127" },
                { "name": "Sector 128" },
                { "name": "Sector 129" },
                { "name": "Sector 130" },
                { "name": "Sector 131" },
                { "name": "Sector 132" },
                { "name": "Sector 133" },
                { "name": "Sector 134" },
                { "name": "Sector 135" },
                { "name": "Sector 136" },
                { "name": "Sector 137" },
                { "name": "Sector 138" },
                { "name": "Sector 139" },
                { "name": "Sector 14" },
                { "name": "Sector 140" },
                { "name": "Sector 141" },
                { "name": "Sector 142" },
                { "name": "Sector 143" },
                { "name": "Sector 144" },
                { "name": "Sector 145" },
                { "name": "Sector 146" },
                { "name": "Sector 147" },
                { "name": "Sector 148" },
                { "name": "Sector 149" },
                { "name": "Sector 15" },
                { "name": "Sector 150" },
                { "name": "Sector 151" },
                { "name": "Sector 152" },
                { "name": "Sector 153" },
                { "name": "Sector 154" },
                { "name": "Sector 155" },
                { "name": "Sector 156" },
                { "name": "Sector 157" },
                { "name": "Sector 158" },
                { "name": "Sector 159" },
                { "name": "Sector 16" },
                { "name": "Sector 160" },
                { "name": "Sector 161" },
                { "name": "Sector 162" },
                { "name": "Sector 163" },
                { "name": "Sector 164" }
                // Add more localities here
            ]

        },
        Bengaluru: {
            bannerImage: "content/img/OIP1.jpg",
            cityLocalitiesList:
                [
                    { "name": "A Narayanapura" },
                    { "name": "Akshya Nagar" },
                    { "name": "Allalasandra" },
                    { "name": "Ambalipura" },
                    { "name": "Anagalapura" },
                    { "name": "Anand Nagar" },
                    { "name": "Azad Nagar" },
                    { "name": "B Narayanapura" },
                    { "name": "Babusapalaya" },
                    { "name": "Bagalakunte" },
                    { "name": "Bagalur" },
                    { "name": "Bagaluru" },
                    { "name": "Bagepalli" },
                    { "name": "Baiyappanahalli" },
                    { "name": "Balagere" },
                    { "name": "Balaji Nagar" },
                    { "name": "Baliganapalli" },
                    { "name": "Banashankari" },
                    { "name": "Banaswadi" },
                    { "name": "Banjara Layout" },
                    { "name": "Bank Avenue Colony" },
                    { "name": "Bannerghatta" },
                    { "name": "Bapuji Nagar" },
                    { "name": "Basapura" },
                    { "name": "Basavanagar" },
                    { "name": "Basavanagudi" },
                    { "name": "Basavanna Nagar" },
                    { "name": "Basaveshwara Nagar" },
                    { "name": "Battarahalli" },
                    { "name": "Begur" },
                    { "name": "Belathur" },
                    { "name": "Bellahalli" },
                    { "name": "Bellandur" },
                    { "name": "Bennigana Halli" },
                    { "name": "Benson Town" },
                    { "name": "Bettahalasur" },
                    { "name": "Bhoganhalli" },
                    { "name": "Bhoopasandra" },
                    { "name": "Bidadi" },
                    { "name": "Bidrahalli" },
                    { "name": "Bikkanahalli" },
                    { "name": "Bilekahalli" },
                    { "name": "Bommanahalli" },
                    { "name": "Bommasandra" },
                    { "name": "Bommenahalli" },
                    { "name": "Brookefield" },
                    { "name": "BTM Layout" },
                    { "name": "Budigere" },
                    { "name": "Budigere Cross" },
                    { "name": "Byatarayanapura" },
                    { "name": "Cambridge Layout" },
                    { "name": "Carmelaram" },
                    { "name": "Challaghatta" },
                    { "name": "Chamarajpet" },
                    { "name": "Channasandra" },
                    { "name": "Cheemasandra" },
                    { "name": "Chickpet" },
                    { "name": "Chikballapur" },
                    { "name": "Chikbanavara" },
                    { "name": "Chikka Tirupathi" },
                    { "name": "Chikkaballapur" },
                    { "name": "Chikkabanavara" },
                    { "name": "Chikkabidarakallu" },
                    { "name": "Chikkalasandra" },
                    { "name": "Chikkanagamangala" },
                    { "name": "Chikkanahalli" },
                    { "name": "Chikkasandra" },
                    { "name": "Chinnapanahalli" },
                    { "name": "Chintamani" },
                    { "name": "Choodasandra" },
                    { "name": "Cooke Town" },
                    { "name": "Cottonpet" },
                    { "name": "Cox Town" },
                    { "name": "Cubbon Park" },
                    { "name": "CV Raman Nagar" },
                    { "name": "Dabaspete" },
                    { "name": "Dasarahalli" },
                    { "name": "Dayananda Nagar" },
                    { "name": "Deepanjali Nagar" },
                    { "name": "Defence Colony" }
                    // Add more localities here
                ]
        },
        Hyderabad: {
            bannerImage: "content/img/OIP1.jpg",
            cityLocalitiesList:
            [
                { "name": "Aghapura" },
                { "name": "Ahmed Nagar" },
                { "name": "Aliabad" },
                { "name": "Ambedkar Nagar" },
                { "name": "Amber Nagar" },
                { "name": "Ameenpur" },
                { "name": "Ameerpet" },
                { "name": "Aminpur" },
                { "name": "Asif Nagar" },
                { "name": "Azamabad" },
                { "name": "Baber Bagh" },
                { "name": "Badangpet" },
                { "name": "Badi Chowdi" },
                { "name": "Bagh Amberpet" },
                { "name": "Bahadurpally" },
                { "name": "Bahadurpura" },
                { "name": "Balamrai" },
                { "name": "Balanagar" },
                { "name": "Balapur" },
                { "name": "Bandimet" },
                { "name": "Bandlaguda" },
                { "name": "Banjara Hills" },
                { "name": "Bapuji Nagar" },
                { "name": "Barkatpura" },
                { "name": "Basheer Bagh" },
                { "name": "Beeramguda" },
                { "name": "Begum Bazaar" },
                { "name": "Begumpet" },
                { "name": "Bhagya Nagar Colony" },
                { "name": "Bharat Nagar" },
                { "name": "Bholakpur" },
                { "name": "Bhuvanagiri" },
                { "name": "Bibinagar" },
                { "name": "BN Reddy Nagar" },
                { "name": "Boiguda" },
                { "name": "Bolarum" },
                { "name": "Borabanda" },
                { "name": "Bowenpally" },
                { "name": "Bowrampet" },
                { "name": "Brahim Patnam" },
                { "name": "Buddha Nagar" },
                { "name": "Chanda Nagar" },
                { "name": "Chandulal Baradari" },
                { "name": "Charlapally" },
                { "name": "Charminar" },
                { "name": "Chatta Bazar" },
                { "name": "Cherlapally" },
                { "name": "Chevalla" },
                { "name": "Chikkadpally" },
                { "name": "Chintal Basti" },
                { "name": "Chintapallyguda" },
                { "name": "Cyberabad" },
                { "name": "Dabeerpura North" },
                { "name": "Dammaiguda" },
                { "name": "Darul Shifa" },
                { "name": "Darus Salam" },
                { "name": "Dasarlapally" },
                { "name": "Dattatreya Colony" },
                { "name": "Devan Devdi" },
                { "name": "Dhoolpet" },
                { "name": "Dilshad Nagar" },
                { "name": "Dilsukh Nagar" },
                { "name": "Dundigal" },
                { "name": "Dwarkapuri Colony" },
                { "name": "East Marredpally" },
                { "name": "Falaknuma" },
                { "name": "Farooqnagar" },
                { "name": "Fateh Maidan" },
                { "name": "Fateh Nagar" },
                { "name": "Feelkhana" },
                { "name": "Film Nagar" },
                { "name": "Financial District" },
                { "name": "Gachibowli" },
                { "name": "Gagan Mahal" },
                { "name": "Gandhi Bhavan" },
                { "name": "Gandhi Nagar" },
                { "name": "Gandipet" },
                { "name": "Ghasmandi" },
                { "name": "Ghatkesar" },
                { "name": "Golconda" }
                // Add more localities here
              ]
              
        },
        Mumbai: {
            bannerImage: "content/img/OIP1.jpg",
            cityLocalitiesList:
                [
                    { "name": "Aarey Milk Colony" },
                    { "name": "Abhyudaya Nagar" },
                    { "name": "Adharwadi" },
                    { "name": "Agripada" },
                    { "name": "Airport Area" },
                    { "name": "Akurli Nagar" },
                    { "name": "Alibag" },
                    { "name": "Ambarnath" },
                    { "name": "Ambedkar Nagar" },
                    { "name": "Ambewadi" },
                    { "name": "Ambivali" },
                    { "name": "Amboli" },
                    { "name": "Anand Nagar" },
                    { "name": "Antop Hill" },
                    { "name": "Apollo Bunder" },
                    { "name": "Asangaon" },
                    { "name": "Asha Nagar" },
                    { "name": "August Kranti Maidan" },
                    { "name": "Azad Nagar" },
                    { "name": "Badlapur" },
                    { "name": "Balkum" },
                    { "name": "Ballard Estate" },
                    { "name": "Bandra East" },
                    { "name": "Bandra Kurla Complex" },
                    { "name": "Bandra West" },
                    { "name": "Bangur Nagar" },
                    { "name": "Bazargate" },
                    { "name": "Behram Baug" },
                    { "name": "Beverly Park" },
                    { "name": "Bhakti Park" },
                    { "name": "Bhandup" },
                    { "name": "Bharat Nagar" },
                    { "name": "Bhayandar" },
                    { "name": "Bhiwandi" },
                    { "name": "Bhuleshwar" },
                    { "name": "BN Bhavan" },
                    { "name": "Boisar" },
                    { "name": "Bolinj" },
                    { "name": "Borivali" },
                    { "name": "BPT Colony" },
                    { "name": "Brahmand" },
                    { "name": "Breach Candy" },
                    { "name": "Byculla" },
                    { "name": "CGS Colony" },
                    { "name": "Chakala" },
                    { "name": "Chamar Baug" },
                    { "name": "Chandan Shanti" },
                    { "name": "Chandivali" },
                    { "name": "Charai" },
                    { "name": "Charkop" },
                    { "name": "Chembur" },
                    { "name": "Chikholi" },
                    { "name": "Chikuwadi" },
                    { "name": "Chinch Bandar" },
                    { "name": "Chincholi Bunder" },
                    { "name": "Chinchpokli" },
                    { "name": "Chiplun" },
                    { "name": "Chira Bazaar" },
                    { "name": "Chowk" },
                    { "name": "Chowpatty" },
                    { "name": "Chuna Bhatti" },
                    { "name": "Churchgate" },
                    { "name": "Colaba" },
                    { "name": "Cotton Green" },
                    { "name": "Cotton Green West" },
                    { "name": "CP Tank" },
                    { "name": "Crawford Market" },
                    { "name": "CST Area" },
                    { "name": "Cuffe Parade" },
                    { "name": "Dadar" },
                    { "name": "Dahisar" },
                    { "name": "Dahivali" },
                    { "name": "Dana Bunder" },
                    { "name": "Danda" },
                    { "name": "Dattapada" },
                    { "name": "Deonar" },
                    { "name": "Devdaya Nagar" },
                    { "name": "Dharavi" },
                    { "name": "Dhobi Ali" },
                    { "name": "Dhobi Talao" },
                    { "name": "Dhokali" },
                    { "name": "Dindoshi" },
                    { "name": "Dockyard" },
                    { "name": "Dombivali" },
                    { "name": "Dongri" },
                    { "name": "Dronagiri" },
                    { "name": "Eden Wood" },
                    { "name": "Eksar" },
                    { "name": "Ekvira Darshan" },
                    { "name": "Evershine Nagar" },
                    { "name": "Flora Fountain" },
                    { "name": "Fort" },
                    { "name": "Four Bungalows" },
                    { "name": "Gamdevi" },
                    { "name": "Gandhi Nagar" },
                    { "name": "Gauripada" },
                    { "name": "Gawand Baug" },
                    { "name": "Ghati Pada" },
                    { "name": "Ghatkopar" },
                    { "name": "Girgaon" },
                    { "name": "Girgaum" },
                    { "name": "Gokul Township" },
                    { "name": "Gokuldham" },
                    { "name": "Gorai" },
                    { "name": "Goregaon" },
                    { "name": "Govandi" },
                    { "name": "Government Colony" },
                    { "name": "Gowalia Tank" },
                    { "name": "Grant Road East" },
                    { "name": "Green Park Extension" },
                    { "name": "GTB Nagar" },
                    { "name": "Gulalwadi" },
                    { "name": "Haji Ali" },
                    { "name": "Hanuman Nagar" },
                    { "name": "Hatkesh Udhog Nagar" },
                    { "name": "Horiman Circle" },
                    { "name": "Hutatma Chowk" },
                    { "name": "Huzefa Nagar" },
                    { "name": "IC Colony" },
                    { "name": "Industrial Area" }
                ]

        },
        Indore: {
            bannerImage: "content/img/OIP1.jpg",
        },
        Chennai: {
            bannerImage: "content/img/OIP1.jpg",
        },
        Pune: {
            bannerImage: "content/img/OIP1.jpg",
        },
        Surat: {
            bannerImage: "content/img/OIP1.jpg",
        },
        Bhopal: {
            bannerImage: "content/img/OIP1.jpg",
        },
        kolkata: {
            bannerImage: "content/img/OIP1.jpg",
        },
        Kanpur:{
            bannerImage: "content/img/OIP1.jpg",
        },
        Lucknow:{
            bannerImage: "content/img/OIP1.jpg",
        },
        Goa:{
            bannerImage: "content/img/OIP1.jpg",
        },
        Jaipur:{
            bannerImage: "content/img/OIP1.jpg",
        },
        Ahmedabad:{
            bannerImage: "content/img/OIP1.jpg",
        },
        Chandigarh:{
            bannerImage: "content/img/OIP1.jpg",
        }
    };

    // Get the city name from the URL
    const urlParams = new URLSearchParams(window.location.search);
   // alert("urlParams" , urlParams)
    const selectedCity = urlParams.get("city");
    //alert("111" , selectedCity)
    var selectedLocality = urlParams.get("locality");
    console.log("selectedLocality" + selectedLocality)
    if (selectedCity && cityData[selectedCity] && selectedLocality === null) {
        console.log("inside selected city")
        cityBanner.src = cityData[selectedCity].bannerImage;
        cityTitle.textContent = "Cooks and Chefs in" + " " + selectedCity;
        citylookingTitle.textContent = "Looking for Chefs and Cooks in " + selectedCity;
        cityDescription.textContent = `Book professional Cooks and Chefs in ${selectedCity} for House Parties, Birthday Parties, Special Breakfast, Lunch and Dinner at Home. Hire trained and verified personal Chefs and Cooks near you for a private dining experience at home with the best cooks and chef services at home.`;
        citySeoContent.textContent = `Online chef for hire in ${selectedCity}, Best caterers for small parties in ${selectedCity}, Best home-made cooking service in ${selectedCity}, Mini party caterers in ${selectedCity}, Book a chef in ${selectedCity}, Book a cook in ${selectedCity}, Book a private chef in ${selectedCity}, Book a private cook in ${selectedCity}, Book a trained verified cook near you in ${selectedCity}, Bookacook in ${selectedCity}, Caterers for small parties in ${selectedCity}, Top caterers in ${selectedCity}, Chef for a party in ${selectedCity}, Catering services in ${selectedCity}, Chef at home service in ${selectedCity}, Chef for a day in ${selectedCity}, Chef for a night in ${selectedCity}, Chef for hire in ${selectedCity}, Chef cooking at my home in ${selectedCity}, Chef near me in ${selectedCity}, Chef on demand in ${selectedCity}, Chef required at home in ${selectedCity}, Chefs for hire in ${selectedCity}, Chefs for home in ${selectedCity}, Hire a private chef in ${selectedCity}, Chefs on hire in ${selectedCity}, Cook chef near me in ${selectedCity}, Cook at home services in ${selectedCity}, Cook for a day in ${selectedCity}, Cook for a night in ${selectedCity}, Cook for one day in ${selectedCity}, Cook for a party in ${selectedCity}, Cook service near me in ${selectedCity}, Cook home services in ${selectedCity}, Cook near me in ${selectedCity}, Cook on demand in ${selectedCity}, Cook on hire near me in ${selectedCity}, Cook required at home in ${selectedCity}, Cooking as a service in ${selectedCity}, Cooking maids near me in ${selectedCity}, Cooking services near me in ${selectedCity}, Cooks for hire in ${selectedCity}, Cooks for home in ${selectedCity}, Cooks near me in ${selectedCity}, Cooks on hire in ${selectedCity}, Domestic cook near me in ${selectedCity}, Find a chef in ${selectedCity}, Find a cook in ${selectedCity}, Hire a chef in ${selectedCity}, Hire a chef for a day in ${selectedCity}, Hire personal chef in ${selectedCity}, Hire a chef for home in ${selectedCity}, Hire a chef near me in ${selectedCity}, Take a Chef in ${selectedCity}, Hire a cook in ${selectedCity}, Hire a cook at home in ${selectedCity}, Hire a cook for home in ${selectedCity}, Hire a cook near me in ${selectedCity}, Hire a personal chef for a night in ${selectedCity}, Hire a personal cook in ${selectedCity}, Hire a professional chef in ${selectedCity}, Hire chef at home in ${selectedCity}, Hire cook near me in ${selectedCity}, Hire cook online in ${selectedCity}, Hire private chef in ${selectedCity}, Hire someone to cook for you in ${selectedCity}, Hiring a personal chef in ${selectedCity}, Home caterers in ${selectedCity}, Home chef near me in ${selectedCity}, Home cook near me in ${selectedCity}, Home cooking service in ${selectedCity}, Home cooking service near me in ${selectedCity}, Home party catering in ${selectedCity}, House chef near me in ${selectedCity}, House cook near me in ${selectedCity}, In-home cooking service in ${selectedCity}, In-house cooking service in ${selectedCity}, Local chefs for hire in ${selectedCity}, Looking for chef in ${selectedCity}, Looking for cook in ${selectedCity}, Mini caterers in ${selectedCity}, Need a chef in ${selectedCity}, Need a cook in ${selectedCity}, Online cook service in ${selectedCity}, Party caterers in ${selectedCity}, Personal chef in ${selectedCity}, Personal chefs for hire near me in ${selectedCity}, Personal Cook in ${selectedCity}, Personal cook near me in ${selectedCity}, Private chef in ${selectedCity}, Private chef hire in ${selectedCity}, Private chef near me in ${selectedCity}, Private chef services near me in ${selectedCity}, Private cook in ${selectedCity}, Private cook for hire in ${selectedCity}, Private personal chef in ${selectedCity}, Professional chef for hire in ${selectedCity}, Top rated chefs in ${selectedCity}, Top rated cooks in ${selectedCity}, Want to hire a cook in ${selectedCity}`;
        cityAreaTitle.textContent = "Serving all Areas in " + selectedCity;
        cityData[selectedCity].cityLocalitiesList.forEach((localityData) => {
            const cityList = document.createElement("a"); // Create an anchor element
            cityList.textContent = localityData.name; // Display the locality title
            const localityDataUrl = localityData.name.replace(/\s+/g, '-');
            cityList.href = 'localities.html?city=' + selectedCity + '&locality=' + localityDataUrl;
            cityArea.appendChild(cityList);
            const currentURL = window.location.href;
            if (currentURL.includes("locality=")) {
                // Extract the base URL (from the beginning to "city.html")
                const cityHtmlIndex = currentURL.indexOf("city.html");

                if (cityHtmlIndex !== -1) {
                    const baseURL = currentURL.slice(0, cityHtmlIndex + 9); // +9 to include "city.html"
                    console.log("baseURL" + baseURL)
                    // Redirect to the base URL without the query parameters
                    window.location.href = baseURL;

                }
            }

        });
    }
    if (selectedLocality) {
        selectedLocality = selectedLocality.replace(/-/g, ' ');
        var selectedLocalityData = cityData[selectedCity].cityLocalitiesList.find((localityData) => localityData.name === selectedLocality);
        console.log("selectedLocalityData" + selectedLocalityData)
    }

    if (selectedLocalityData) {
        // You can now access the selected locality's data
        localityBanner.src = "content/img/OIP1.jpg";
        localityTitle.textContent = "Cooks and Chefs in " + selectedLocalityData.name;
        localitylookingTitle.textContent = "Looking for Chefs and Cooks in " + selectedLocalityData.name;
        localityDescription.textContent = `Book professional Cooks and Chefs in ${selectedLocalityData.name} ${selectedCity} for House Parties, Birthday Parties, Special Breakfast, Lunch and Dinner at Home. Hire trained and verified personal Chefs and Cooks near you for a private dining experience at home with the best cooks and chef services at home.`;
        localitySeoContent.textContent = `Online chef for hire in ${selectedLocalityData.name}, Best caterers for small parties in ${selectedLocalityData.name}, Best home-made cooking service in ${selectedLocalityData.name}, Mini party caterers in ${selectedLocalityData.name}, Book a chef in ${selectedLocalityData.name}, Book a cook in ${selectedLocalityData.name}, Book a private chef in ${selectedLocalityData.name}, Book a private cook in ${selectedLocalityData.name}, Book a trained verified cook near you in ${selectedLocalityData.name}, Bookacook in ${selectedLocalityData.name}, Caterers for small parties in ${selectedLocalityData.name}, Top caterers in ${selectedLocalityData.name}, Chef for a party in ${selectedLocalityData.name}, Catering services in ${selectedLocalityData.name}, Chef at home service in ${selectedLocalityData.name}, Chef for a day in ${selectedLocalityData.name}, Chef for a night in ${selectedLocalityData.name}, Chef for hire in ${selectedLocalityData.name}, Chef cooking at my home in ${selectedLocalityData.name}, Chef near me in ${selectedLocalityData.name}, Chef on demand in ${selectedLocalityData.name}, Chef required at home in ${selectedLocalityData.name}, Chefs for hire in ${selectedLocalityData.name}, Chefs for home in ${selectedLocalityData.name}, Hire a private chef in ${selectedLocalityData.name}, Chefs on hire in ${selectedLocalityData.name}, Cook chef near me in ${selectedLocalityData.name}, Cook at home services in ${selectedLocalityData.name}, Cook for a day in ${selectedLocalityData.name}, Cook for a night in ${selectedLocalityData.name}, Cook for one day in ${selectedLocalityData.name}, Cook for a party in ${selectedLocalityData.name}, Cook service near me in ${selectedLocalityData.name}, Cook home services in ${selectedLocalityData.name}, Cook near me in ${selectedLocalityData.name}, Cook on demand in ${selectedLocalityData.name}, Cook on hire near me in ${selectedLocalityData.name}, Cook required at home in ${selectedLocalityData.name}, Cooking as a service in ${selectedLocalityData.name}, Cooking maids near me in ${selectedLocalityData.name}, Cooking services near me in ${selectedLocalityData.name}, Cooks for hire in ${selectedLocalityData.name}, Cooks for home in ${selectedLocalityData.name}, Cooks near me in ${selectedLocalityData.name}, Cooks on hire in ${selectedLocalityData.name}, Domestic cook near me in ${selectedLocalityData.name}, Find a chef in ${selectedLocalityData.name}, Find a cook in ${selectedLocalityData.name}, Hire a chef in ${selectedLocalityData.name}, Hire a chef for a day in ${selectedLocalityData.name}, Hire personal chef in ${selectedLocalityData.name}, Hire a chef for home in ${selectedLocalityData.name}, Hire a chef near me in ${selectedLocalityData.name}, Take a Chef in ${selectedLocalityData.name}, Hire a cook in ${selectedLocalityData.name}, Hire a cook at home in ${selectedLocalityData.name}, Hire a cook for home in ${selectedLocalityData.name}, Hire a cook near me in ${selectedLocalityData.name}, Hire a personal chef for a night in ${selectedLocalityData.name}, Hire a personal cook in ${selectedLocalityData.name}, Hire a professional chef in ${selectedLocalityData.name}, Hire chef at home in ${selectedLocalityData.name}, Hire cook near me in ${selectedLocalityData.name}, Hire cook online in ${selectedLocalityData.name}, Hire private chef in ${selectedLocalityData.name}, Hire someone to cook for you in ${selectedLocalityData.name}, Hiring a personal chef in ${selectedLocalityData.name}, Home caterers in ${selectedLocalityData.name}, Home chef near me in ${selectedLocalityData.name}, Home cook near me in ${selectedLocalityData.name}, Home cooking service in ${selectedLocalityData.name}, Home cooking service near me in ${selectedLocalityData.name}, Home party catering in ${selectedLocalityData.name}, House chef near me in ${selectedLocalityData.name}, House cook near me in ${selectedLocalityData.name}, In-home cooking service in ${selectedLocalityData.name}, In-house cooking service in ${selectedLocalityData.name}, Local chefs for hire in ${selectedLocalityData.name}, Looking for chef in ${selectedLocalityData.name}, Looking for cook in ${selectedLocalityData.name}, Mini caterers in ${selectedLocalityData.name}, Need a chef in ${selectedLocalityData.name}, Need a cook in ${selectedLocalityData.name}, Online cook service in ${selectedLocalityData.name}, Party caterers in ${selectedLocalityData.name}, Personal chef in ${selectedLocalityData.name}, Personal chefs for hire near me in ${selectedLocalityData.name}, Personal Cook in ${selectedLocalityData.name}, Personal cook near me in ${selectedLocalityData.name}, Private chef in ${selectedLocalityData.name}, Private chef hire in ${selectedLocalityData.name}, Private chef near me in ${selectedLocalityData.name}, Private chef services near me in ${selectedLocalityData.name}, Private cook in ${selectedLocalityData.name}, Private cook for hire in ${selectedLocalityData.name}, Private personal chef in ${selectedLocalityData.name}, Professional chef for hire in ${selectedLocalityData.name}, Top rated chefs in ${selectedLocalityData.name}, Top rated cooks in ${selectedLocalityData.name}, Want to hire a cook in ${selectedLocalityData.name}`;
    }
});